### PR TITLE
Clean up our package.json

### PR DESCRIPTION
**Pull request by byronhulcher**
https://docs.npmjs.com/cli/run-script
>In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix.

✨ BEST PRACTICES✨

### CODE REVIEW

**Comment by nelsonpecora** [comment]
👍

**Comment by nelsonpecora** [comment]
this is already done?

**Comment by byronhulcher** [comment]
@nelsonpecora minor conflict from when I did the prepublish change

**Comment by nelsonpecora** [comment]
👍

**Pull request merged**
