### PR TITLE
account for border-width in medium toolbar

### PR DESCRIPTION
**Pull request by cruzanmo**
Before:
image

After:
image

### CODE REVIEW

**Comment by amycheng** [comment]
:+1:

**Comment by gloddy** [comment]
It's visually awkward to put the down arrow between two buttons. I'd suggest moving it to the second permanently.

**Comment by gloddy** [comment]
screen shot 2016-08-24 at 10 17 56 am

**Comment by gloddy** [comment]
@cruzanmo Also, do you want a "A1" svg for the button with a font that matches the others?

**Pull request merged**
