### PR TITLE
update kiln to use page.url

### PR DESCRIPTION
**Pull request by yoshokatana**
* refactored and simplified `edit.publishPage`
* refactoed and simplified `edit.unpublishPage`
* removed extraneous methods in `edit` services
* added `dom.pageUri` method to get page uri (useful for stubbing when testing)
* simplified `page-state` service

### CODE REVIEW

**Comment by cruzanmo** [comment]
Nice, look at all that code go

**Comment by yoshokatana** [comment]
This won't _really_ work until this amphora issue is fixed: https://github.com/nymag/amphora/issues/185

**Comment by yoshokatana** [comment]
Also depends on https://github.com/nymag/amphora/issues/187 which should be done by noon tomorrow (per @TakenPilot)

**Comment by yoshokatana** [comment]
Amphora stuff is merged in.

**Pull request merged**
