### PR TITLE
Added button type to component list buttons

### PR DESCRIPTION
**Pull request by jonwinton**
This is a fix for issue #435 

Added the `type="button"` to the `component-list` buttons

### CODE REVIEW

**Comment by davidandrewfrey** [comment]
👍

**Comment by byronhulcher** [comment]
👍

**Comment by jonwinton** [comment]
@yoshokatana would this qualify as a bug fix and need a `np patch`?

**Comment by byronhulcher** [comment]
@jonwinton I think a patch would be fine.

**Pull request merged**
